export const MOTIVATIONAL_MESSAGES = [
    "Um passo de cada vez, com Deus tudo é possível! ✨",
    "Você é mais forte do que imagina. Continue firme! 💪",
    "A disciplina é a ponte entre suas metas e suas realizações. 🌉",
    "Que sua vontade de vencer seja maior que qualquer obstáculo. 🚀",
    "O Senhor é o seu refúgio e fortaleza. Avante! 🙏",
    "Não pare até se orgulhar de você mesmo! ⭐",
    "Tudo posso Naquele que me fortalece. Vamos lá! ❤️",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia. 🔥",
    "Deus tem planos incríveis para quem não desiste. Creia! 🙌",
    "Sua jornada é única. Aproveite cada progresso! 🌈",
    "Foco, força e fé. O topo te espera! 🏔️",
    "Transforme sua rotina em um ato de gratidão e progresso. 🕊️",
    "Missão cumprida! Mais uma vitória pra sua arena pessoal 🏆",
    "Hoje você jogou como um verdadeiro Rei lendário 👑",
    "Tarefa feita! Seu castelo ficou mais forte hoje 💪",
    "Vitória diária garantida — continue subindo de arena 🚀",
    "Você não deu rage quit. Jogada perfeita! 🔥",
    "Mais um dia, mais uma coroa conquistada 👑",
    "Deck bem montado e tarefa concluída com sucesso 🃏",
    "O esforço de hoje é o elixir da sua evolução ⚡",
    "Defesa sólida, ataque certeiro — tarefa completa 🛡️⚔️",
    "Você jogou no modo campeão hoje. Continue assim! 🏆"
];

export const LANDSCAPES = [
    // --- Arenas de Progressão (0 a 20 + Lendária) ---
  '/assets/bg-arenas/bg-campo-de-treinamento.avif',
  '/assets/bg-arenas/bg-estadio-goblin.avif',
  '/assets/bg-arenas/bg-fosso-dos-ossos.avif',
  '/assets/bg-arenas/bg-torneio-barbaro.avif',
  '/assets/bg-arenas/bg-parquinho-da-pekka.avif',
  '/assets/bg-arenas/bg-vale-dos-feiticos.avif',
  '/assets/bg-arenas/bg-oficina-do-construtor.avif',
  '/assets/bg-arenas/bg-arena-real.avif',
  '/assets/bg-arenas/bg-pico-congelado.avif',
  '/assets/bg-arenas/bg-arena-da-selva.avif',
  '/assets/bg-arenas/bg-montanha-do-porco.avif',
  '/assets/bg-arenas/bg-eletrovale.avif',
  '/assets/bg-arenas/bg-cidade-assombrada.avif',
  '/assets/bg-arenas/bg-covil-dos-patifes.avif',
  '/assets/bg-arenas/bg-pico-sereno.avif',
  '/assets/bg-arenas/bg-mina-do-mineiro.avif',
  '/assets/bg-arenas/bg-cozinha-do-executor.avif',
  '/assets/bg-arenas/bg-cripta-real.avif',
  '/assets/bg-arenas/bg-santuario-silencioso.avif',
  '/assets/bg-arenas/bg-spa-de-dragoes.avif',
  '/assets/bg-arenas/bg-campo-de-treino.avif',
  '/assets/bg-arenas/bg-clash-fest.avif',
  '/assets/bg-arenas/bg-arena-panquecas.avif',
  '/assets/bg-arenas/bg-valkalla.avif',
  '/assets/bg-arenas/bg-arena-lendaria.avif',
  '/assets/bg-arenas/bg-cabana-do-amor-do-lenhador.avif',
  '/assets/bg-arenas/bg-estrada-real.avif',
  '/assets/bg-arenas/bg-rua-da-mosqueteira.avif',
  '/assets/bg-arenas/bg-apice-dos-herois.avif',

  // --- Arenas de Temporada e Especiais (Ordem de Lançamento/Temática) ---
  '/assets/bg-arenas/bg-batalha-na-praia.avif',
  '/assets/bg-arenas/bg-arena-do-barco.avif',
  '/assets/bg-arenas/bg-shocktober.avif',
  '/assets/bg-arenas/bg-festa-goblin.avif',
  '/assets/bg-arenas/bg-clash-natalino.avif',
  '/assets/bg-arenas/bg-palacio-proibido.avif',
  '/assets/bg-arenas/bg-aniversario.avif',
  '/assets/bg-arenas/bg-deposito-de-sucata.avif',
  '/assets/bg-arenas/bg-combate-de-dragoes.avif',
  '/assets/bg-arenas/bg-sonho-do-principe.avif',
  '/assets/bg-arenas/bg-coliseu-guerra-de-clas.avif',
  '/assets/bg-arenas/bg-shocktober-lendaria.avif',
  '/assets/bg-arenas/bg-vila-assombrada.avif',
  '/assets/bg-arenas/bg-clashmas-aconchegante.avif',
  '/assets/bg-arenas/bg-palacio-ancestral.avif',
  '/assets/bg-arenas/bg-fervor-ardente.avif',
  '/assets/bg-arenas/bg-goblin-bonanza.avif',
  '/assets/bg-arenas/bg-rock-n-royale.avif',
  '/assets/bg-arenas/bg-loucura-magica.avif',
  '/assets/bg-arenas/bg-vila-barbara-8-bit.avif',
  '/assets/bg-arenas/bg-fosso-de-lama.avif',
  '/assets/bg-arenas/bg-noite-de-luta.avif',
  '/assets/bg-arenas/bg-frank-halloween.avif',
  '/assets/bg-arenas/bg-nono-aniversario.avif',
  '/assets/bg-arenas/bg-origens-das-evolucoes.avif',
  '/assets/bg-arenas/bg-minas-goblin.avif',
  '/assets/bg-arenas/bg-arena-do-rock.avif',
  '/assets/bg-arenas/bg-arena-da-taverna.avif',
  '/assets/bg-arenas/bg-arena-gigante-das-runas.avif',
  '/assets/bg-arenas/bg-arena-da-imperatriz-espiritual.avif',
  '/assets/bg-arenas/bg-bebe-dragao.avif',
  '/assets/bg-arenas/bg-dia-dos-namorados.avif',
  '/assets/bg-arenas/bg-marcha-dos-mortos-vivos.avif',
  '/assets/bg-arenas/bg-velho-oeste.avif',
  '/assets/bg-arenas/bg-valentines-day.avif',

   // --- Rota das Lendas e Ligas ---
  '/assets/bg-arenas/bg-rota-das-lendas.avif',
  '/assets/bg-arenas/bg-liga1.avif',
  '/assets/bg-arenas/bg-liga2.avif',
  '/assets/bg-arenas/bg-liga3.avif',
  '/assets/bg-arenas/bg-liga4.avif',
  '/assets/bg-arenas/bg-liga5.avif',
  '/assets/bg-arenas/bg-liga6.avif',
  '/assets/bg-arenas/bg-liga7.avif',
  '/assets/bg-arenas/bg-liga8.avif',
  '/assets/bg-arenas/bg-liga9.avif',
  '/assets/bg-arenas/bg-liga10.avif',
];

export const ARENAS = [
  // --- Arenas de Progressão (0 a 20 + Lendária) ---
  '/assets/arenas/campo-de-treinamento.avif',
  '/assets/arenas/estadio-goblin.avif',
  '/assets/arenas/fosso-dos-ossos.avif',
  '/assets/arenas/torneio-barbaro.avif',
  '/assets/arenas/parquinho-da-pekka.avif',
  '/assets/arenas/vale-dos-feiticos.avif',
  '/assets/arenas/oficina-do-construtor.avif',
  '/assets/arenas/arena-real.avif',
  '/assets/arenas/pico-congelado.avif',
  '/assets/arenas/arena-da-selva.avif',
  '/assets/arenas/montanha-do-porco.avif',
  '/assets/arenas/eletrovale.avif',
  '/assets/arenas/cidade-assombrada.avif',
  '/assets/arenas/covil-dos-patifes.avif',
  '/assets/arenas/pico-sereno.avif',
  '/assets/arenas/mina-do-mineiro.avif',
  '/assets/arenas/cozinha-do-executor.avif',
  '/assets/arenas/cripta-real.avif',
  '/assets/arenas/santuario-silencioso.avif',
  '/assets/arenas/spa-de-dragoes.avif',
  '/assets/arenas/campo-de-treino.avif',
  '/assets/arenas/clash-fest.avif',
  '/assets/arenas/arena-panquecas.avif',
  '/assets/arenas/valkalla.avif',
  '/assets/arenas/arena-lendaria.avif',
  '/assets/arenas/cabana-do-amor-do-lenhador.avif',
  '/assets/arenas/estrada-real.avif',
  '/assets/arenas/rua-da-mosqueteira.avif',
  '/assets/arenas/apice-dos-herois.avif',

  // --- Arenas de Temporada e Especiais (Ordem de Lançamento/Temática) ---
  '/assets/arenas/batalha-na-praia.avif',
  '/assets/arenas/arena-do-barco.avif',
  '/assets/arenas/shocktober.avif',
  '/assets/arenas/festa-goblin.avif',
  '/assets/arenas/clash-natalino.avif',
  '/assets/arenas/palacio-proibido.avif',
  '/assets/arenas/aniversario.avif',
  '/assets/arenas/deposito-de-sucata.avif',
  '/assets/arenas/combate-de-dragoes.avif',
  '/assets/arenas/sonho-do-principe.avif',
  '/assets/arenas/coliseu-guerra-de-clas.avif',
  '/assets/arenas/shocktober-lendaria.avif',
  '/assets/arenas/vila-assombrada.avif',
  '/assets/arenas/clashmas-aconchegante.avif',
  '/assets/arenas/palacio-ancestral.avif',
  '/assets/arenas/fervor-ardente.avif',
  '/assets/arenas/goblin-bonanza.avif',
  '/assets/arenas/rock-n-royale.avif',
  '/assets/arenas/loucura-magica.avif',
  '/assets/arenas/vila-barbara-8-bit.avif',
  '/assets/arenas/fosso-de-lama.avif',
  '/assets/arenas/noite-de-luta.avif',
  '/assets/arenas/frank-halloween.avif',
  '/assets/arenas/nono-aniversario.avif',
  '/assets/arenas/origens-das-evolucoes.avif',
  '/assets/arenas/minas-goblin.avif',
  '/assets/arenas/arena-do-rock.avif',
  '/assets/arenas/arena-da-taverna.avif',
  '/assets/arenas/arena-gigante-das-runas.avif',
  '/assets/arenas/arena-da-imperatriz-espiritual.avif',
  '/assets/arenas/bebe-dragao.avif',
  '/assets/arenas/dia-dos-namorados.avif',
  '/assets/arenas/marcha-dos-mortos-vivos.avif',
  '/assets/arenas/velho-oeste.avif',
  '/assets/arenas/valentines-day.avif',

   // --- Rota das Lendas e Ligas ---
  '/assets/arenas/rota-das-lendas.avif',
  '/assets/arenas/liga1.avif',
  '/assets/arenas/liga2.avif',
  '/assets/arenas/liga3.avif',
  '/assets/arenas/liga4.avif',
  '/assets/arenas/liga5.avif',
  '/assets/arenas/liga6.avif',
  '/assets/arenas/liga7.avif',
  '/assets/arenas/liga8.avif',
  '/assets/arenas/liga9.avif',
  '/assets/arenas/liga10.avif',
];

export const BALLOON_COLORS = [
    'text-red-600 drop-shadow-md',
    'text-blue-600 drop-shadow-md',
    'text-yellow-500 drop-shadow-md',
    'text-green-600 drop-shadow-md',
    'text-purple-600 drop-shadow-md',
    'text-pink-600 drop-shadow-md'
];


